services:
  ia:
    image: ia
    container_name: ia
    networks:
      - nn
    volumes:
     - ./zzz:/app/saves
  nn:
    image: nn
    container_name: nn
    networks:
      - nn
    ports:
      - "8080:8080"
networks:
   nn:
      driver: bridge

